# .scrutinizer.yml

# filter:
#     excluded_paths:
#                 - [react_native/coverage/*, react_native/__test/__*]
filter:
    excluded_paths:
        - "react_native/coverage/"
        - "react_native/__test__/"

build:
  nodes:  // behöver bog lägga till en environment
    coverage:
      tests:
        override:
          - command: npm --prefix /home/scrutinizer/build/react_native run test
            coverage:
              file: react_native/coverage/clover.xml
              format: clover


# # Mikaels kod:
# imports:    // <------------
#     - php

# filter:
#     excluded_paths: [vendor/*, test/*]

# build:
#     nodes:
#         my-tests:
#             environment:  // <------------
#                 php:
#                     version: 8.1
#         analysis:
#             tests:
#                 override:
#                     - php-scrutinizer-run // <------------ kanske detta?
#     tests:
#         override:
#             -
#                 command: "composer phpunit"
#                 coverage:
#                     file: "build/coverage.clover"
#                     format: "php-clover"



          # - command: npm --prefix /home/scrutinizer/build/react_native i --force && npm --prefix /home/scrutinizer/build/react_native run test



