# .scrutinizer.yml

# filter:
#     excluded_paths:
#                 - [react_native/coverage/*, react_native/__test/__*]
filter:
    excluded_paths:
        - "react_native/coverage/"
        - "react_native/__test__/"

build:
  nodes:
    coverage:
      tests:
        override:
          - command: npm --prefix /home/scrutinizer/build/react_native i --force && npm --prefix /home/scrutinizer/build/react_native run test
            coverage:
              file: react_native/coverage/clover.xml
              format: clover



