version: "3.7"
services:
  react_native:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: webapp
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
      - '19000:19000'
    healthcheck:
      disable: true