version: '2.4'

services:
  react_native:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
      - '19000:19000'
    volumes:
      - ./react_native:/opt/react_native/app:delegated
      - ./react_native/package.json:/opt/react_native/package.json
      - ./react_native/package-lock.json:/opt/react_native/package-lock.json
      - notused:/opt/react_native/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused: